apiVersion: v1
kind: Service
metadata:
  name: host-network
spec:
  type: NodePort
  selector:
    service: host-network
  clusterIP: '10.111.111.112'
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32090
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: host-network
spec:
  replicas: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: host-network
    spec:
      terminationGracePeriodSeconds: 120
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 1
          timeoutSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 2
