version: '2'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis
    ports:
        - '6380:6379'
    networks:
      - default
      - manual_bridge

networks:
  manual_bridge:
    external: true
